services:
  database:
    image: postgis/postgis
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=listing_service
    ports:
      - '5432:5432'
    volumes:
      - data-volume:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U root -d listing_service']
      interval: 1s
      timeout: 5s
      retries: 5
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    volumes:
      - ./:/app
    environment:
      - DATABASE_URL=postgres://root:password@database:5432/listing_service?sslmode=disable
    depends_on:
      database:
        condition: service_healthy
volumes:
  data-volume:
